language: julia
os:
  - linux
  - osx
julia:
  - 1.0
  - 1.4
  - nightly
addons:
  apt:
    packages:
    - python3-pygraphviz
    - ghostscript
codecov: true
jobs:
  allow_failures:
    - julia: nightly
